---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/3 15:38
---

if redis.call("get",KEYS[1])==ARGV[1] then
    redis.call("set",KEYS[1],ARGV[2])
    return true
else
    return false
end