/*
 * -------------------------------声明-------------------------------------------
 *	<auto-generated>
 *		此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
 *		模板名称：{{DomainName}}Starter.java.tt
 *	</auto-generated>
 * ------------------------------------------------------------------------------
 */
package com.zjk.hy;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * 项目启动类
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication springApplication = new SpringApplication(Application.class);
        springApplication.run(args);
    }
}



